/*
Deployment script for NewDataBase

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "NewDataBase"
:setvar DefaultFilePrefix "NewDataBase"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER01\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Creating Table [dbo].[BlackList]...';


GO
CREATE TABLE [dbo].[BlackList] (
    [BlackListStatus] VARCHAR (10) NOT NULL,
    [ProjectName]     VARCHAR (50) NOT NULL,
    [ClientIDNumber]  INT          NOT NULL,
    CONSTRAINT [PK_BlackList] PRIMARY KEY CLUSTERED ([BlackListStatus] ASC)
);


GO
PRINT N'Creating Index [dbo].[BlackList].[NonClusteredIndex-Projects]...';


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-Projects]
    ON [dbo].[BlackList]([ProjectName] ASC)
    INCLUDE([ClientIDNumber]);


GO
PRINT N'Creating Table [dbo].[ClientAddresses]...';


GO
CREATE TABLE [dbo].[ClientAddresses] (
    [ClientAddress]              VARCHAR (50) NOT NULL,
    [ClientIDNumber]             INT          NOT NULL,
    [DistanceFromAhitofelOffice] TINYINT      NOT NULL,
    CONSTRAINT [PK_ClientAddresses] PRIMARY KEY CLUSTERED ([ClientAddress] ASC, [ClientIDNumber] ASC)
);


GO
PRINT N'Creating Index [dbo].[ClientAddresses].[NonClusteredIndex-ClientAddress]...';


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-ClientAddress]
    ON [dbo].[ClientAddresses]([ClientAddress] ASC);


GO
PRINT N'Creating Index [dbo].[ClientAddresses].[NonClusteredIndex-DistanceFromAhitofelOffice]...';


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-DistanceFromAhitofelOffice]
    ON [dbo].[ClientAddresses]([DistanceFromAhitofelOffice] ASC);


GO
PRINT N'Creating Table [dbo].[Clients]...';


GO
CREATE TABLE [dbo].[Clients] (
    [ClientName]      VARCHAR (20) NOT NULL,
    [ClientIDNumber]  INT          NOT NULL,
    [LocalForeign]    VARCHAR (7)  NOT NULL,
    [BlackListStatus] VARCHAR (10) NULL,
    [TeamName]        VARCHAR (10) NOT NULL,
    [IDNumber]        VARCHAR (10) NOT NULL,
    CONSTRAINT [PK_Clients] PRIMARY KEY CLUSTERED ([ClientIDNumber] ASC),
    CONSTRAINT [UQ__Clients__65800DA0DA0F687B] UNIQUE NONCLUSTERED ([ClientName] ASC)
);


GO
PRINT N'Creating Index [dbo].[Clients].[NonClusteredIndex-BlackList]...';


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-BlackList]
    ON [dbo].[Clients]([BlackListStatus] ASC);


GO
PRINT N'Creating Index [dbo].[Clients].[NonClusteredIndex-LocalForeign]...';


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-LocalForeign]
    ON [dbo].[Clients]([LocalForeign] ASC);


GO
PRINT N'Creating Index [dbo].[Clients].[NonClusteredIndex-ClientName]...';


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-ClientName]
    ON [dbo].[Clients]([ClientName] ASC);


GO
PRINT N'Creating Table [dbo].[ClientsInvoicing]...';


GO
CREATE TABLE [dbo].[ClientsInvoicing] (
    [ClientIDNumber]                               INT            NOT NULL,
    [ProjectName]                                  VARCHAR (50)   NOT NULL,
    [CostOfHoursDrivingToClientAndBack]            SMALLINT       NOT NULL,
    [ConsultantMonthlyNumberOfHoursinProject]      NUMERIC (7, 2) NOT NULL,
    [MyMonth]                                      DATE           NOT NULL,
    [IDNumber]                                     VARCHAR (10)   NOT NULL,
    [ConsultantProjectMonthInvoiceAmountBeforeVAT] INT            NOT NULL,
    [ConsultantProjectMonthInvoiceAmountAfterVAT]  INT            NOT NULL,
    [InvoiceAmountPaid]                            DATE           NULL,
    [ExchangeRateDate]                             DATE           NOT NULL,
    CONSTRAINT [PK_ClientsInvoicing_1] PRIMARY KEY CLUSTERED ([ClientIDNumber] ASC, [ProjectName] ASC, [MyMonth] ASC, [IDNumber] ASC)
);


GO
PRINT N'Creating Index [dbo].[ClientsInvoicing].[NonClusteredIndex-ConsultantMonthlyNumberOfHoursinProject]...';


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-ConsultantMonthlyNumberOfHoursinProject]
    ON [dbo].[ClientsInvoicing]([ConsultantMonthlyNumberOfHoursinProject] ASC);


GO
PRINT N'Creating Table [dbo].[Configurations1]...';


GO
CREATE TABLE [dbo].[Configurations1] (
    [NekudotZikuyMan]                    NUMERIC (4, 2) NOT NULL,
    [NekudotZikuyWoman]                  NUMERIC (4, 2) NOT NULL,
    [NekudotZikuyForEachMansChild]       NUMERIC (4, 2) NOT NULL,
    [NekudotZikuyForEachWomansChild]     NUMERIC (4, 2) NOT NULL,
    [SocialBenefitPercentage1]           NUMERIC (4, 2) NOT NULL,
    [SocialBenefitPercentage2]           NUMERIC (4, 2) NOT NULL,
    [ManagementIncreasePercentage]       NUMERIC (4, 2) NOT NULL,
    [VAT]                                NUMERIC (4, 2) NOT NULL,
    [SaturdayTaarifIncrease]             NUMERIC (4, 2) NOT NULL,
    [HolidayTaarifIncrease]              NUMERIC (4, 2) NOT NULL,
    [SaturdayHolidayTaarifIncrease]      NUMERIC (4, 2) NOT NULL,
    [TakingOutFromBlackListTaarif]       NUMERIC (4, 2) NOT NULL,
    [AdditionalHoursIncrease]            NUMERIC (4, 2) NOT NULL,
    [RecordSavingNumberOfYears]          TINYINT        NOT NULL,
    [CostOfHourlyDrivingToClientAndBack] SMALLINT       NOT NULL,
    [MaxAgeChild]                        TINYINT        NOT NULL
);


GO
PRINT N'Creating Table [dbo].[Consultants]...';


GO
CREATE TABLE [dbo].[Consultants] (
    [IDNumber]                          VARCHAR (10) NOT NULL,
    [FirstName]                         VARCHAR (10) NOT NULL,
    [LatName]                           VARCHAR (10) NOT NULL,
    [AddressPrimary]                    VARCHAR (30) NOT NULL,
    [AddressSecondary]                  VARCHAR (30) NULL,
    [MeritalStatus]                     VARCHAR (10) NOT NULL,
    [Gender]                            VARCHAR (10) NOT NULL,
    [TeamManagerYesNo]                  VARCHAR (3)  NOT NULL,
    [TeamName]                          VARCHAR (10) NOT NULL,
    [NonTeamConsultingClient]           INT          NULL,
    [StatusOfEmploymentActiveDissmised] VARCHAR (10) NOT NULL,
    [NumberOfKidsUnder18]               TINYINT      NOT NULL,
    [ProjectName]                       VARCHAR (50) NOT NULL,
    [ClientIDNumber]                    INT          NOT NULL,
    [SpouseFirstName]                   VARCHAR (10) NULL,
    [SpouseLastName]                    VARCHAR (10) NULL,
    [SpouseIDNumber]                    VARCHAR (10) NULL,
    [SpouseAddress]                     VARCHAR (50) NULL,
    [SpouseGender]                      VARCHAR (10) NULL,
    CONSTRAINT [PK_Consultants] PRIMARY KEY CLUSTERED ([IDNumber] ASC)
);


GO
PRINT N'Creating Index [dbo].[Consultants].[NonClusteredIndex-20210825-131039]...';


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-20210825-131039]
    ON [dbo].[Consultants]([SpouseIDNumber] ASC);


GO
PRINT N'Creating Index [dbo].[Consultants].[NonClusteredIndex-TeamManagerYesNo]...';


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-TeamManagerYesNo]
    ON [dbo].[Consultants]([TeamManagerYesNo] ASC);


GO
PRINT N'Creating Index [dbo].[Consultants].[NonClusteredIndex-Gender]...';


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-Gender]
    ON [dbo].[Consultants]([Gender] ASC);


GO
PRINT N'Creating Index [dbo].[Consultants].[NonClusteredIndex-MeritalStatus]...';


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-MeritalStatus]
    ON [dbo].[Consultants]([MeritalStatus] ASC);


GO
PRINT N'Creating Table [dbo].[ConsultantSalaries_History]...';


GO
CREATE TABLE [dbo].[ConsultantSalaries_History] (
    [ProjectName]                          VARCHAR (50)  NOT NULL,
    [VacationDays]                         TINYINT       NULL,
    [AdditionalHours]                      TINYINT       NULL,
    [IDNumber]                             VARCHAR (10)  NOT NULL,
    [TaarifFixedForConsultant]             SMALLINT      NOT NULL,
    [Month]                                DATE          NOT NULL,
    [ValidFrom]                            DATETIME2 (7) NOT NULL,
    [ValidTo]                              DATETIME2 (7) NOT NULL,
    [ActualWorkingHoursPerMonth]           TINYINT       NOT NULL,
    [ActualWorkingHoursPerMonthForPayment] TINYINT       NOT NULL
);


GO
PRINT N'Creating Index [dbo].[ConsultantSalaries_History].[ix_ConsultantSalaries_History]...';


GO
CREATE CLUSTERED INDEX [ix_ConsultantSalaries_History]
    ON [dbo].[ConsultantSalaries_History]([ValidTo] ASC, [ValidFrom] ASC) WITH (DATA_COMPRESSION = PAGE);


GO
PRINT N'Creating Table [dbo].[ExchangeRates$]...';


GO
CREATE TABLE [dbo].[ExchangeRates$] (
    [ExchangeRateDate]      DATE           NOT NULL,
    [ILSDollarExchangerate] NUMERIC (4, 2) NOT NULL,
    CONSTRAINT [PK_ExchangeRates$] PRIMARY KEY CLUSTERED ([ExchangeRateDate] ASC)
);


GO
PRINT N'Creating Index [dbo].[ExchangeRates$].[NonClusteredIndex-ILSDollarExchangerate]...';


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-ILSDollarExchangerate]
    ON [dbo].[ExchangeRates$]([ILSDollarExchangerate] ASC);


GO
PRINT N'Creating Table [dbo].[HagimOrSaturday]...';


GO
CREATE TABLE [dbo].[HagimOrSaturday] (
    [DateInYear] DATE         NOT NULL,
    [HagName]    VARCHAR (20) NULL,
    [IsSaturday] VARCHAR (3)  NULL,
    [MyMonth]    DATE         NOT NULL,
    CONSTRAINT [PK_HagimOrSaturday] PRIMARY KEY CLUSTERED ([DateInYear] ASC)
);


GO
PRINT N'Creating Index [dbo].[HagimOrSaturday].[NonClusteredIndex-HagName]...';


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-HagName]
    ON [dbo].[HagimOrSaturday]([HagName] ASC);


GO
PRINT N'Creating Table [dbo].[Hearings]...';


GO
CREATE TABLE [dbo].[Hearings] (
    [UpdatingHRDpt]                       VARCHAR (50)  NOT NULL,
    [HearingSummon]                       VARCHAR (50)  NOT NULL,
    [HearingDate]                         DATE          NOT NULL,
    [HearingSummary]                      VARCHAR (100) NOT NULL,
    [HearingDismissalDecision]            VARCHAR (10)  NOT NULL,
    [WarningComment1]                     VARCHAR (50)  NOT NULL,
    [WarningComment2]                     VARCHAR (50)  NOT NULL,
    [DismissalInfo]                       VARCHAR (50)  NOT NULL,
    [IssuanceOfLetterToNationalInsurance] VARCHAR (10)  NOT NULL,
    [InquiryNumber]                       INT           NOT NULL,
    [HearingNumber]                       INT           IDENTITY (1, 1) NOT NULL,
    [IDNumber]                            VARCHAR (10)  NOT NULL,
    CONSTRAINT [PK_Hearings] PRIMARY KEY CLUSTERED ([HearingNumber] ASC)
);


GO
PRINT N'Creating Index [dbo].[Hearings].[NonClusteredIndex-HearingDate]...';


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-HearingDate]
    ON [dbo].[Hearings]([HearingDate] ASC);


GO
PRINT N'Creating Table [dbo].[InquiryFearOfFraudsAndHearings]...';


GO
CREATE TABLE [dbo].[InquiryFearOfFraudsAndHearings] (
    [IDNumber]                     VARCHAR (10)  NOT NULL,
    [DescriptionOfIncident]        VARCHAR (50)  NOT NULL,
    [InquiryNumber]                INT           IDENTITY (1, 1) NOT NULL,
    [SchedulingInquiryWithManager] DATE          NOT NULL,
    [InquiryDocumentation]         VARCHAR (100) NOT NULL,
    [ReportError]                  VARCHAR (10)  NULL,
    CONSTRAINT [PK_InquiryFearOfFrauds] PRIMARY KEY CLUSTERED ([InquiryNumber] ASC)
);


GO
PRINT N'Creating Index [dbo].[InquiryFearOfFraudsAndHearings].[NonClusteredIndex-SchedulingInquiryWithManager]...';


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-SchedulingInquiryWithManager]
    ON [dbo].[InquiryFearOfFraudsAndHearings]([SchedulingInquiryWithManager] ASC);


GO
PRINT N'Creating Table [dbo].[Kids]...';


GO
CREATE TABLE [dbo].[Kids] (
    [KidFirstName]   VARCHAR (10) NOT NULL,
    [KidLastName]    VARCHAR (10) NOT NULL,
    [KidDateOfBirth] DATE         NOT NULL,
    [KidIDNumber]    VARCHAR (10) NOT NULL,
    [KidAddress]     VARCHAR (50) NOT NULL,
    [IDNumber]       VARCHAR (10) NOT NULL,
    CONSTRAINT [PK_Kids] PRIMARY KEY CLUSTERED ([KidIDNumber] ASC)
);


GO
PRINT N'Creating Index [dbo].[Kids].[NonClusteredIndex-KidDateOfBirth]...';


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-KidDateOfBirth]
    ON [dbo].[Kids]([KidDateOfBirth] ASC);


GO
PRINT N'Creating Table [dbo].[MyMonth]...';


GO
CREATE TABLE [dbo].[MyMonth] (
    [MyMonth]                                  DATE NOT NULL,
    [ConsultantSalary]                         INT  NOT NULL,
    [PaymentsReceivedFromClientsforConsultant] INT  NOT NULL,
    CONSTRAINT [PK_MyMonth] PRIMARY KEY CLUSTERED ([MyMonth] ASC)
);


GO
PRINT N'Creating Index [dbo].[MyMonth].[NonClusteredIndex-PaymentsReceivedFromClientsforConsultant]...';


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-PaymentsReceivedFromClientsforConsultant]
    ON [dbo].[MyMonth]([PaymentsReceivedFromClientsforConsultant] ASC);


GO
PRINT N'Creating Index [dbo].[MyMonth].[NonClusteredIndex-ConsultantSalary]...';


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-ConsultantSalary]
    ON [dbo].[MyMonth]([ConsultantSalary] ASC);


GO
PRINT N'Creating Table [dbo].[ProfitAnalysisSurveys]...';


GO
CREATE TABLE [dbo].[ProfitAnalysisSurveys] (
    [ProfitLoss]                                         INT          NOT NULL,
    [Month]                                              DATE         NOT NULL,
    [IDNumber]                                           VARCHAR (10) NOT NULL,
    [TotaPaidToConsultantInTheMonth]                     SMALLINT     NOT NULL,
    [TotalAmountInvoicedToClientInTheMonthPerConsultant] SMALLINT     NOT NULL,
    CONSTRAINT [PK_ProfitAnalysisSurveys_1] PRIMARY KEY CLUSTERED ([Month] ASC, [IDNumber] ASC)
);


GO
PRINT N'Creating Index [dbo].[ProfitAnalysisSurveys].[NonClusteredIndex-ProfitLoss]...';


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-ProfitLoss]
    ON [dbo].[ProfitAnalysisSurveys]([ProfitLoss] ASC);


GO
PRINT N'Creating Table [dbo].[ProjectConsultantTaarifs_History]...';


GO
CREATE TABLE [dbo].[ProjectConsultantTaarifs_History] (
    [ProjectName] VARCHAR (50)   NOT NULL,
    [IDNumber]    VARCHAR (10)   NOT NULL,
    [Taarif]      NUMERIC (7, 2) NOT NULL,
    [Currency]    VARCHAR (10)   NOT NULL,
    [MyMonth]     DATE           NOT NULL,
    [ValidFrom]   DATETIME2 (7)  NOT NULL,
    [ValidTo]     DATETIME2 (7)  NOT NULL
);


GO
PRINT N'Creating Index [dbo].[ProjectConsultantTaarifs_History].[ix_ProjectConsultantTaarifs_History]...';


GO
CREATE CLUSTERED INDEX [ix_ProjectConsultantTaarifs_History]
    ON [dbo].[ProjectConsultantTaarifs_History]([ValidTo] ASC, [ValidFrom] ASC) WITH (DATA_COMPRESSION = PAGE);


GO
PRINT N'Creating Table [dbo].[ProjectCoordinatorsOnBehalfOfClients]...';


GO
CREATE TABLE [dbo].[ProjectCoordinatorsOnBehalfOfClients] (
    [ProjectCoordinatorName]                  VARCHAR (50) NOT NULL,
    [ProjectCoordinatorAddress]               VARCHAR (50) NOT NULL,
    [ProjectCoordinatorBirthDate]             DATE         NOT NULL,
    [ProjectCoordinatorCakePrefernce]         VARCHAR (10) NOT NULL,
    [ProjectName]                             VARCHAR (50) NOT NULL,
    [ReportsToSeniorManagerName]              VARCHAR (50) NULL,
    [SeniorProjectManagerName]                VARCHAR (50) NULL,
    [ClientIDNumber]                          INT          NOT NULL,
    [SeniorProjectManagerNameYesNo]           VARCHAR (50) NULL,
    [SeniorProjectManagerSpouseName]          VARCHAR (50) NULL,
    [SeniorProjectManagerSpouseBirthDate]     DATE         NULL,
    [SeniorProjectManagerSpouseCakePrefernce] VARCHAR (50) NULL,
    CONSTRAINT [PK_ProjectCoordinatorsOnBehalfOfClients] PRIMARY KEY CLUSTERED ([ProjectCoordinatorName] ASC, [ProjectName] ASC),
    UNIQUE NONCLUSTERED ([ProjectCoordinatorName] ASC)
);


GO
PRINT N'Creating Index [dbo].[ProjectCoordinatorsOnBehalfOfClients].[NonClusteredIndex-ProjectCoordinatorName]...';


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-ProjectCoordinatorName]
    ON [dbo].[ProjectCoordinatorsOnBehalfOfClients]([ProjectCoordinatorName] ASC);


GO
PRINT N'Creating Index [dbo].[ProjectCoordinatorsOnBehalfOfClients].[NonClusteredIndex-ProjectCoordinatorBirthDate]...';


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-ProjectCoordinatorBirthDate]
    ON [dbo].[ProjectCoordinatorsOnBehalfOfClients]([ProjectCoordinatorBirthDate] ASC);


GO
PRINT N'Creating Table [dbo].[Projects]...';


GO
CREATE TABLE [dbo].[Projects] (
    [ProjectName]            VARCHAR (50) NOT NULL,
    [OutofBlackListByInsist] VARCHAR (10) NULL,
    [TeamName]               VARCHAR (10) NOT NULL,
    [ClientIDNumber]         INT          NOT NULL,
    [BlackListStatus]        VARCHAR (10) NULL,
    [IDNumber]               VARCHAR (10) NOT NULL,
    CONSTRAINT [PK_Projects] PRIMARY KEY CLUSTERED ([ProjectName] ASC)
);


GO
PRINT N'Creating Index [dbo].[Projects].[NonClusteredIndex-OutofBlackListByInsist]...';


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-OutofBlackListByInsist]
    ON [dbo].[Projects]([OutofBlackListByInsist] ASC);


GO
PRINT N'Creating Table [dbo].[SeniorProjectManagerKids]...';


GO
CREATE TABLE [dbo].[SeniorProjectManagerKids] (
    [ProjectCoordinatorName]               VARCHAR (50) NOT NULL,
    [SeniorProjectManagerKidBirthDate]     DATE         NOT NULL,
    [SeniorProjectManagerKidCakePrefernce] VARCHAR (50) NOT NULL,
    CONSTRAINT [PK_SeniorProjectManagerKids] PRIMARY KEY CLUSTERED ([SeniorProjectManagerKidBirthDate] ASC)
);


GO
PRINT N'Creating Index [dbo].[SeniorProjectManagerKids].[NonClusteredIndex-SeniorMangerKidDate]...';


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-SeniorMangerKidDate]
    ON [dbo].[SeniorProjectManagerKids]([SeniorProjectManagerKidBirthDate] ASC);


GO
PRINT N'Creating Table [dbo].[Teams_History]...';


GO
CREATE TABLE [dbo].[Teams_History] (
    [TeamName]  VARCHAR (10)  NOT NULL,
    [ValidFrom] DATETIME2 (7) NOT NULL,
    [ValidTo]   DATETIME2 (7) NOT NULL
);


GO
PRINT N'Creating Index [dbo].[Teams_History].[ix_Teams_History]...';


GO
CREATE CLUSTERED INDEX [ix_Teams_History]
    ON [dbo].[Teams_History]([ValidTo] ASC, [ValidFrom] ASC) WITH (DATA_COMPRESSION = PAGE);


GO
PRINT N'Creating Table [dbo].[WorkingHours]...';


GO
CREATE TABLE [dbo].[WorkingHours] (
    [IDNumber]       VARCHAR (10) NOT NULL,
    [ProjectName]    VARCHAR (50) NOT NULL,
    [DateOfWork]     DATE         NOT NULL,
    [StartHour]      TIME (7)     NOT NULL,
    [EndHour]        TIME (7)     NOT NULL,
    [InquiryNumber]  INT          NULL,
    [ClientIDNumber] INT          NOT NULL,
    CONSTRAINT [PK_WorkingHours] PRIMARY KEY CLUSTERED ([IDNumber] ASC, [ProjectName] ASC, [DateOfWork] ASC, [StartHour] ASC)
);


GO
PRINT N'Creating Index [dbo].[WorkingHours].[NonClusteredIndex-IDNumber]...';


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-IDNumber]
    ON [dbo].[WorkingHours]([IDNumber] ASC);


GO
PRINT N'Creating Index [dbo].[WorkingHours].[NonClusteredIndex-ProjectName]...';


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-ProjectName]
    ON [dbo].[WorkingHours]([ProjectName] ASC);


GO
PRINT N'Creating Index [dbo].[WorkingHours].[NonClusteredIndex-DateOfWork]...';


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-DateOfWork]
    ON [dbo].[WorkingHours]([DateOfWork] ASC);


GO
PRINT N'Creating Table [dbo].[WorkingHoursPerMonth]...';


GO
CREATE TABLE [dbo].[WorkingHoursPerMonth] (
    [WorkingMonth]                   DATE    NOT NULL,
    [NumberOfWorkingHoursInTheMonth] TINYINT NOT NULL,
    CONSTRAINT [PK_WorkingHoursPerMonth_1] PRIMARY KEY CLUSTERED ([WorkingMonth] ASC, [NumberOfWorkingHoursInTheMonth] ASC)
);


GO
PRINT N'Creating Table [dbo].[ConsultantSalaries]...';


GO
CREATE TABLE [dbo].[ConsultantSalaries] (
    [ProjectName]                          VARCHAR (50)                                NOT NULL,
    [VacationDays]                         TINYINT                                     NULL,
    [AdditionalHours]                      TINYINT                                     NULL,
    [IDNumber]                             VARCHAR (10)                                NOT NULL,
    [TaarifFixedForConsultant]             SMALLINT                                    NOT NULL,
    [Month]                                DATE                                        NOT NULL,
    [ValidFrom]                            DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
    [ValidTo]                              DATETIME2 (7) GENERATED ALWAYS AS ROW END   NOT NULL,
    [ActualWorkingHoursPerMonth]           TINYINT                                     NOT NULL,
    [ActualWorkingHoursPerMonthForPayment] TINYINT                                     NOT NULL,
    CONSTRAINT [PK_ConsultantSalaries_1] PRIMARY KEY CLUSTERED ([IDNumber] ASC, [Month] ASC),
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[dbo].[ConsultantSalaries_History], DATA_CONSISTENCY_CHECK=ON));


GO
PRINT N'Creating Index [dbo].[ConsultantSalaries].[NonClusteredIndex-Taarif]...';


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-Taarif]
    ON [dbo].[ConsultantSalaries]([TaarifFixedForConsultant] ASC);


GO
PRINT N'Creating Table [dbo].[ProjectConsultantTaarifs]...';


GO
CREATE TABLE [dbo].[ProjectConsultantTaarifs] (
    [ProjectName] VARCHAR (50)                                NOT NULL,
    [IDNumber]    VARCHAR (10)                                NOT NULL,
    [Taarif]      NUMERIC (7, 2)                              NOT NULL,
    [Currency]    VARCHAR (10)                                NOT NULL,
    [MyMonth]     DATE                                        NOT NULL,
    [ValidFrom]   DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
    [ValidTo]     DATETIME2 (7) GENERATED ALWAYS AS ROW END   NOT NULL,
    CONSTRAINT [PK_ProjectConsultantTaarifs_1] PRIMARY KEY CLUSTERED ([ProjectName] ASC, [IDNumber] ASC),
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[dbo].[ProjectConsultantTaarifs_History], DATA_CONSISTENCY_CHECK=ON));


GO
PRINT N'Creating Index [dbo].[ProjectConsultantTaarifs].[NonClusteredIndex-Currency]...';


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-Currency]
    ON [dbo].[ProjectConsultantTaarifs]([Currency] ASC);


GO
PRINT N'Creating Index [dbo].[ProjectConsultantTaarifs].[NonClusteredIndex-Taarif]...';


GO
CREATE NONCLUSTERED INDEX [NonClusteredIndex-Taarif]
    ON [dbo].[ProjectConsultantTaarifs]([Taarif] ASC);


GO
PRINT N'Creating Table [dbo].[Teams]...';


GO
CREATE TABLE [dbo].[Teams] (
    [TeamName]  VARCHAR (10)                                NOT NULL,
    [ValidFrom] DATETIME2 (7) GENERATED ALWAYS AS ROW START NOT NULL,
    [ValidTo]   DATETIME2 (7) GENERATED ALWAYS AS ROW END   NOT NULL,
    CONSTRAINT [PK_Teams] PRIMARY KEY CLUSTERED ([TeamName] ASC),
    PERIOD FOR SYSTEM_TIME ([ValidFrom], [ValidTo])
)
WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[dbo].[Teams_History], DATA_CONSISTENCY_CHECK=ON));


GO
PRINT N'Creating Default Constraint [dbo].[DF_Clients_BlackList]...';


GO
ALTER TABLE [dbo].[Clients]
    ADD CONSTRAINT [DF_Clients_BlackList] DEFAULT ('No') FOR [BlackListStatus];


GO
PRINT N'Creating Default Constraint [dbo].[DF_Projects_BlackListStatus]...';


GO
ALTER TABLE [dbo].[Projects]
    ADD CONSTRAINT [DF_Projects_BlackListStatus] DEFAULT ('No') FOR [BlackListStatus];


GO
PRINT N'Creating Foreign Key [dbo].[FK_ClientAddresses_Clients]...';


GO
ALTER TABLE [dbo].[ClientAddresses] WITH NOCHECK
    ADD CONSTRAINT [FK_ClientAddresses_Clients] FOREIGN KEY ([ClientIDNumber]) REFERENCES [dbo].[Clients] ([ClientIDNumber]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Clients_BlackList]...';


GO
ALTER TABLE [dbo].[Clients] WITH NOCHECK
    ADD CONSTRAINT [FK_Clients_BlackList] FOREIGN KEY ([BlackListStatus]) REFERENCES [dbo].[BlackList] ([BlackListStatus]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Clients_Consultants]...';


GO
ALTER TABLE [dbo].[Clients] WITH NOCHECK
    ADD CONSTRAINT [FK_Clients_Consultants] FOREIGN KEY ([IDNumber]) REFERENCES [dbo].[Consultants] ([IDNumber]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Clients_Teams]...';


GO
ALTER TABLE [dbo].[Clients] WITH NOCHECK
    ADD CONSTRAINT [FK_Clients_Teams] FOREIGN KEY ([TeamName]) REFERENCES [dbo].[Teams] ([TeamName]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ClientsInvoicing_Clients]...';


GO
ALTER TABLE [dbo].[ClientsInvoicing] WITH NOCHECK
    ADD CONSTRAINT [FK_ClientsInvoicing_Clients] FOREIGN KEY ([ClientIDNumber]) REFERENCES [dbo].[Clients] ([ClientIDNumber]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ClientsInvoicing_Consultants]...';


GO
ALTER TABLE [dbo].[ClientsInvoicing] WITH NOCHECK
    ADD CONSTRAINT [FK_ClientsInvoicing_Consultants] FOREIGN KEY ([IDNumber]) REFERENCES [dbo].[Consultants] ([IDNumber]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ClientsInvoicing_ExchangeRates$]...';


GO
ALTER TABLE [dbo].[ClientsInvoicing] WITH NOCHECK
    ADD CONSTRAINT [FK_ClientsInvoicing_ExchangeRates$] FOREIGN KEY ([ExchangeRateDate]) REFERENCES [dbo].[ExchangeRates$] ([ExchangeRateDate]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ClientsInvoicing_MyMonth]...';


GO
ALTER TABLE [dbo].[ClientsInvoicing] WITH NOCHECK
    ADD CONSTRAINT [FK_ClientsInvoicing_MyMonth] FOREIGN KEY ([MyMonth]) REFERENCES [dbo].[MyMonth] ([MyMonth]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ClientsInvoicing_Projects]...';


GO
ALTER TABLE [dbo].[ClientsInvoicing] WITH NOCHECK
    ADD CONSTRAINT [FK_ClientsInvoicing_Projects] FOREIGN KEY ([ProjectName]) REFERENCES [dbo].[Projects] ([ProjectName]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Consultants_Clients1]...';


GO
ALTER TABLE [dbo].[Consultants] WITH NOCHECK
    ADD CONSTRAINT [FK_Consultants_Clients1] FOREIGN KEY ([ClientIDNumber]) REFERENCES [dbo].[Clients] ([ClientIDNumber]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Consultants_Projects]...';


GO
ALTER TABLE [dbo].[Consultants] WITH NOCHECK
    ADD CONSTRAINT [FK_Consultants_Projects] FOREIGN KEY ([ProjectName]) REFERENCES [dbo].[Projects] ([ProjectName]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Consultants_Teams]...';


GO
ALTER TABLE [dbo].[Consultants] WITH NOCHECK
    ADD CONSTRAINT [FK_Consultants_Teams] FOREIGN KEY ([TeamName]) REFERENCES [dbo].[Teams] ([TeamName]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ConsultantSalaries_Consultants]...';


GO
ALTER TABLE [dbo].[ConsultantSalaries] WITH NOCHECK
    ADD CONSTRAINT [FK_ConsultantSalaries_Consultants] FOREIGN KEY ([IDNumber]) REFERENCES [dbo].[Consultants] ([IDNumber]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ConsultantSalaries_MyMonth]...';


GO
ALTER TABLE [dbo].[ConsultantSalaries] WITH NOCHECK
    ADD CONSTRAINT [FK_ConsultantSalaries_MyMonth] FOREIGN KEY ([Month]) REFERENCES [dbo].[MyMonth] ([MyMonth]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_HagimOrSaturday_MyMonth]...';


GO
ALTER TABLE [dbo].[HagimOrSaturday] WITH NOCHECK
    ADD CONSTRAINT [FK_HagimOrSaturday_MyMonth] FOREIGN KEY ([MyMonth]) REFERENCES [dbo].[MyMonth] ([MyMonth]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Hearings_Consultants]...';


GO
ALTER TABLE [dbo].[Hearings] WITH NOCHECK
    ADD CONSTRAINT [FK_Hearings_Consultants] FOREIGN KEY ([IDNumber]) REFERENCES [dbo].[Consultants] ([IDNumber]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Hearings_InquiryFearOfFraudsAndHearings]...';


GO
ALTER TABLE [dbo].[Hearings] WITH NOCHECK
    ADD CONSTRAINT [FK_Hearings_InquiryFearOfFraudsAndHearings] FOREIGN KEY ([InquiryNumber]) REFERENCES [dbo].[InquiryFearOfFraudsAndHearings] ([InquiryNumber]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_InquiryFearOfFraudsAndHearings_Consultants]...';


GO
ALTER TABLE [dbo].[InquiryFearOfFraudsAndHearings] WITH NOCHECK
    ADD CONSTRAINT [FK_InquiryFearOfFraudsAndHearings_Consultants] FOREIGN KEY ([IDNumber]) REFERENCES [dbo].[Consultants] ([IDNumber]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Kids_Consultants]...';


GO
ALTER TABLE [dbo].[Kids] WITH NOCHECK
    ADD CONSTRAINT [FK_Kids_Consultants] FOREIGN KEY ([IDNumber]) REFERENCES [dbo].[Consultants] ([IDNumber]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ProfitAnalysisSurveys_Consultants]...';


GO
ALTER TABLE [dbo].[ProfitAnalysisSurveys] WITH NOCHECK
    ADD CONSTRAINT [FK_ProfitAnalysisSurveys_Consultants] FOREIGN KEY ([IDNumber]) REFERENCES [dbo].[Consultants] ([IDNumber]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ProfitAnalysisSurveys_MyMonth]...';


GO
ALTER TABLE [dbo].[ProfitAnalysisSurveys] WITH NOCHECK
    ADD CONSTRAINT [FK_ProfitAnalysisSurveys_MyMonth] FOREIGN KEY ([Month]) REFERENCES [dbo].[MyMonth] ([MyMonth]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ProjectConsultantTaarifs_Consultants]...';


GO
ALTER TABLE [dbo].[ProjectConsultantTaarifs] WITH NOCHECK
    ADD CONSTRAINT [FK_ProjectConsultantTaarifs_Consultants] FOREIGN KEY ([IDNumber]) REFERENCES [dbo].[Consultants] ([IDNumber]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ProjectConsultantTaarifs_MyMonth]...';


GO
ALTER TABLE [dbo].[ProjectConsultantTaarifs] WITH NOCHECK
    ADD CONSTRAINT [FK_ProjectConsultantTaarifs_MyMonth] FOREIGN KEY ([MyMonth]) REFERENCES [dbo].[MyMonth] ([MyMonth]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ProjectConsultantTaarifs_Projects]...';


GO
ALTER TABLE [dbo].[ProjectConsultantTaarifs] WITH NOCHECK
    ADD CONSTRAINT [FK_ProjectConsultantTaarifs_Projects] FOREIGN KEY ([ProjectName]) REFERENCES [dbo].[Projects] ([ProjectName]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ProjectCoordinatorsOnBehalfOfClients_Clients]...';


GO
ALTER TABLE [dbo].[ProjectCoordinatorsOnBehalfOfClients] WITH NOCHECK
    ADD CONSTRAINT [FK_ProjectCoordinatorsOnBehalfOfClients_Clients] FOREIGN KEY ([ClientIDNumber]) REFERENCES [dbo].[Clients] ([ClientIDNumber]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ProjectCoordinatorsOnBehalfOfClients_ProjectCoordinatorsOnBehalfOfClients]...';


GO
ALTER TABLE [dbo].[ProjectCoordinatorsOnBehalfOfClients] WITH NOCHECK
    ADD CONSTRAINT [FK_ProjectCoordinatorsOnBehalfOfClients_ProjectCoordinatorsOnBehalfOfClients] FOREIGN KEY ([ReportsToSeniorManagerName]) REFERENCES [dbo].[ProjectCoordinatorsOnBehalfOfClients] ([ProjectCoordinatorName]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_ProjectCoordinatorsOnBehalfOfClients_Projects]...';


GO
ALTER TABLE [dbo].[ProjectCoordinatorsOnBehalfOfClients] WITH NOCHECK
    ADD CONSTRAINT [FK_ProjectCoordinatorsOnBehalfOfClients_Projects] FOREIGN KEY ([ProjectName]) REFERENCES [dbo].[Projects] ([ProjectName]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Projects_BlackList]...';


GO
ALTER TABLE [dbo].[Projects] WITH NOCHECK
    ADD CONSTRAINT [FK_Projects_BlackList] FOREIGN KEY ([BlackListStatus]) REFERENCES [dbo].[BlackList] ([BlackListStatus]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Projects_Clients]...';


GO
ALTER TABLE [dbo].[Projects] WITH NOCHECK
    ADD CONSTRAINT [FK_Projects_Clients] FOREIGN KEY ([ClientIDNumber]) REFERENCES [dbo].[Clients] ([ClientIDNumber]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Projects_Consultants]...';


GO
ALTER TABLE [dbo].[Projects] WITH NOCHECK
    ADD CONSTRAINT [FK_Projects_Consultants] FOREIGN KEY ([IDNumber]) REFERENCES [dbo].[Consultants] ([IDNumber]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_Projects_Teams]...';


GO
ALTER TABLE [dbo].[Projects] WITH NOCHECK
    ADD CONSTRAINT [FK_Projects_Teams] FOREIGN KEY ([TeamName]) REFERENCES [dbo].[Teams] ([TeamName]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_SeniorProjectManagerKids_ProjectCoordinatorsOnBehalfOfClients]...';


GO
ALTER TABLE [dbo].[SeniorProjectManagerKids] WITH NOCHECK
    ADD CONSTRAINT [FK_SeniorProjectManagerKids_ProjectCoordinatorsOnBehalfOfClients] FOREIGN KEY ([ProjectCoordinatorName]) REFERENCES [dbo].[ProjectCoordinatorsOnBehalfOfClients] ([ProjectCoordinatorName]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_WorkingHours_Clients]...';


GO
ALTER TABLE [dbo].[WorkingHours] WITH NOCHECK
    ADD CONSTRAINT [FK_WorkingHours_Clients] FOREIGN KEY ([ClientIDNumber]) REFERENCES [dbo].[Clients] ([ClientIDNumber]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_WorkingHours_Consultants]...';


GO
ALTER TABLE [dbo].[WorkingHours] WITH NOCHECK
    ADD CONSTRAINT [FK_WorkingHours_Consultants] FOREIGN KEY ([IDNumber]) REFERENCES [dbo].[Consultants] ([IDNumber]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_WorkingHours_InquiryFearOfFraudsAndHearings]...';


GO
ALTER TABLE [dbo].[WorkingHours] WITH NOCHECK
    ADD CONSTRAINT [FK_WorkingHours_InquiryFearOfFraudsAndHearings] FOREIGN KEY ([InquiryNumber]) REFERENCES [dbo].[InquiryFearOfFraudsAndHearings] ([InquiryNumber]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_WorkingHours_Projects]...';


GO
ALTER TABLE [dbo].[WorkingHours] WITH NOCHECK
    ADD CONSTRAINT [FK_WorkingHours_Projects] FOREIGN KEY ([ProjectName]) REFERENCES [dbo].[Projects] ([ProjectName]);


GO
PRINT N'Creating Foreign Key [dbo].[FK_WorkingHoursPerMonth_MyMonth]...';


GO
ALTER TABLE [dbo].[WorkingHoursPerMonth] WITH NOCHECK
    ADD CONSTRAINT [FK_WorkingHoursPerMonth_MyMonth] FOREIGN KEY ([WorkingMonth]) REFERENCES [dbo].[MyMonth] ([MyMonth]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[ClientAddresses] WITH CHECK CHECK CONSTRAINT [FK_ClientAddresses_Clients];

ALTER TABLE [dbo].[Clients] WITH CHECK CHECK CONSTRAINT [FK_Clients_BlackList];

ALTER TABLE [dbo].[Clients] WITH CHECK CHECK CONSTRAINT [FK_Clients_Consultants];

ALTER TABLE [dbo].[Clients] WITH CHECK CHECK CONSTRAINT [FK_Clients_Teams];

ALTER TABLE [dbo].[ClientsInvoicing] WITH CHECK CHECK CONSTRAINT [FK_ClientsInvoicing_Clients];

ALTER TABLE [dbo].[ClientsInvoicing] WITH CHECK CHECK CONSTRAINT [FK_ClientsInvoicing_Consultants];

ALTER TABLE [dbo].[ClientsInvoicing] WITH CHECK CHECK CONSTRAINT [FK_ClientsInvoicing_ExchangeRates$];

ALTER TABLE [dbo].[ClientsInvoicing] WITH CHECK CHECK CONSTRAINT [FK_ClientsInvoicing_MyMonth];

ALTER TABLE [dbo].[ClientsInvoicing] WITH CHECK CHECK CONSTRAINT [FK_ClientsInvoicing_Projects];

ALTER TABLE [dbo].[Consultants] WITH CHECK CHECK CONSTRAINT [FK_Consultants_Clients1];

ALTER TABLE [dbo].[Consultants] WITH CHECK CHECK CONSTRAINT [FK_Consultants_Projects];

ALTER TABLE [dbo].[Consultants] WITH CHECK CHECK CONSTRAINT [FK_Consultants_Teams];

ALTER TABLE [dbo].[ConsultantSalaries] WITH CHECK CHECK CONSTRAINT [FK_ConsultantSalaries_Consultants];

ALTER TABLE [dbo].[ConsultantSalaries] WITH CHECK CHECK CONSTRAINT [FK_ConsultantSalaries_MyMonth];

ALTER TABLE [dbo].[HagimOrSaturday] WITH CHECK CHECK CONSTRAINT [FK_HagimOrSaturday_MyMonth];

ALTER TABLE [dbo].[Hearings] WITH CHECK CHECK CONSTRAINT [FK_Hearings_Consultants];

ALTER TABLE [dbo].[Hearings] WITH CHECK CHECK CONSTRAINT [FK_Hearings_InquiryFearOfFraudsAndHearings];

ALTER TABLE [dbo].[InquiryFearOfFraudsAndHearings] WITH CHECK CHECK CONSTRAINT [FK_InquiryFearOfFraudsAndHearings_Consultants];

ALTER TABLE [dbo].[Kids] WITH CHECK CHECK CONSTRAINT [FK_Kids_Consultants];

ALTER TABLE [dbo].[ProfitAnalysisSurveys] WITH CHECK CHECK CONSTRAINT [FK_ProfitAnalysisSurveys_Consultants];

ALTER TABLE [dbo].[ProfitAnalysisSurveys] WITH CHECK CHECK CONSTRAINT [FK_ProfitAnalysisSurveys_MyMonth];

ALTER TABLE [dbo].[ProjectConsultantTaarifs] WITH CHECK CHECK CONSTRAINT [FK_ProjectConsultantTaarifs_Consultants];

ALTER TABLE [dbo].[ProjectConsultantTaarifs] WITH CHECK CHECK CONSTRAINT [FK_ProjectConsultantTaarifs_MyMonth];

ALTER TABLE [dbo].[ProjectConsultantTaarifs] WITH CHECK CHECK CONSTRAINT [FK_ProjectConsultantTaarifs_Projects];

ALTER TABLE [dbo].[ProjectCoordinatorsOnBehalfOfClients] WITH CHECK CHECK CONSTRAINT [FK_ProjectCoordinatorsOnBehalfOfClients_Clients];

ALTER TABLE [dbo].[ProjectCoordinatorsOnBehalfOfClients] WITH CHECK CHECK CONSTRAINT [FK_ProjectCoordinatorsOnBehalfOfClients_ProjectCoordinatorsOnBehalfOfClients];

ALTER TABLE [dbo].[ProjectCoordinatorsOnBehalfOfClients] WITH CHECK CHECK CONSTRAINT [FK_ProjectCoordinatorsOnBehalfOfClients_Projects];

ALTER TABLE [dbo].[Projects] WITH CHECK CHECK CONSTRAINT [FK_Projects_BlackList];

ALTER TABLE [dbo].[Projects] WITH CHECK CHECK CONSTRAINT [FK_Projects_Clients];

ALTER TABLE [dbo].[Projects] WITH CHECK CHECK CONSTRAINT [FK_Projects_Consultants];

ALTER TABLE [dbo].[Projects] WITH CHECK CHECK CONSTRAINT [FK_Projects_Teams];

ALTER TABLE [dbo].[SeniorProjectManagerKids] WITH CHECK CHECK CONSTRAINT [FK_SeniorProjectManagerKids_ProjectCoordinatorsOnBehalfOfClients];

ALTER TABLE [dbo].[WorkingHours] WITH CHECK CHECK CONSTRAINT [FK_WorkingHours_Clients];

ALTER TABLE [dbo].[WorkingHours] WITH CHECK CHECK CONSTRAINT [FK_WorkingHours_Consultants];

ALTER TABLE [dbo].[WorkingHours] WITH CHECK CHECK CONSTRAINT [FK_WorkingHours_InquiryFearOfFraudsAndHearings];

ALTER TABLE [dbo].[WorkingHours] WITH CHECK CHECK CONSTRAINT [FK_WorkingHours_Projects];

ALTER TABLE [dbo].[WorkingHoursPerMonth] WITH CHECK CHECK CONSTRAINT [FK_WorkingHoursPerMonth_MyMonth];


GO
PRINT N'Update complete.';


GO
